### ISSUE TITLE
Intermittent Bad request

### ISSUE THREAD

**Issue by it-spiderman** [inblockio/micro-PKC#104]
From time to time, apache returns BadRequest error.

Apache error - header too long, we need to increase the limit

HW to investigate after holidays

**Comment by it-spiderman** [comment]
This seems to work:
in `/etc/apache2/sites-enabled/000-default.conf` put `LimitRequestFieldSize 16384` and restart apache (or container)

We will see if this is a proper fix after the holidays

**Comment by FantasticoFox** [comment]
I could not reproduce the problem anymore.
