### ISSUE TITLE
Ethereum Login button broken in Brave Browser with Metamask

### ISSUE THREAD

**Issue by dykstranet** [inblockio/micro-PKC#107]
`Ethereum Login` button does nothing when pushed.

Environment:
Operating System: Manjaro Linux
KDE Plasma Version: 5.23.4
KDE Frameworks Version: 5.89.0
Qt Version: 5.15.2
Kernel Version: 5.10.89-1-MANJARO (64-bit)
Graphics Platform: X11
Processors: 4 × Intel® Core™ i7-10510U CPU @ 1.80GHz
Memory: 15.2 GiB of RAM
Graphics Processor: Mesa Intel® UHD Graphics

Brave Version:
Version 1.33.106 Chromium: 96.0.4664.110 (Official Build) unknown (64-bit)

Could be related to this error from the browser execution log. 
```
inpage.js:1 Uncaught Error: MetaMask detected another web3.
     MetaMask will not work reliably with another web3 extension.
     This usually happens if you have two MetaMasks installed,
     or MetaMask and another web3 extension. Please remove one
     and try again.
    at Object.<anonymous> (inpage.js:1)
    at Object.<anonymous> (inpage.js:1)
    at Object.1../lib/setupWeb3.js (inpage.js:1)
    at i (inpage.js:1)
    at e (inpage.js:1)
    at inpage.js:1
```
See also regarding use of [web3](https://docs.metamask.io/guide/provider-migration.html#replacing-window-web3).

This problem goes away when using Chromium browser. 
![Ethereum_login_prob_2022-01-06_13-53](https://user-images.githubusercontent.com/4895224/148335569-dbfcee6f-5e53-4f37-9394-c1b78b7022c4.png)
![Ethereum_login_prob_2022-01-06_13-53](https://user-images.githubusercontent.com/4895224/148335642-5ea80ecf-619e-4b2a-b96f-cf3d3b9411f5.png)

**Comment by rht** [comment]
> inpage.js:1 Uncaught Error: MetaMask detected another web3.

This is most likely because you have Brave wallet installed and enabled.

**Comment by dykstranet** [comment]
Yes! 

To fix, if ON, toggle to OFF the "Crypto Wallets" setting in  `Manage Extensions`.
![disable_crypto_wallets_arrow_2022-01-06_17-05](https://user-images.githubusercontent.com/4895224/148358082-9fa17182-a21c-4643-aede-f1027b12ba69.png)

When "Crypto Wallets" toggled to OFF, Metamask login works.
