### ISSUE TITLE
micro-PKC using Depricated windo.web3 API?

### ISSUE THREAD

**Issue by dykstranet** [inblockio/micro-PKC#114]
Getting a warning in metamask
![web3_depricaed_2022-01-09_10-43](https://user-images.githubusercontent.com/4895224/148667807-4ff9e581-f183-44cc-bc60-6711d7f4661a.png)

**Comment by FantasticoFox** [comment]
Can you please provide the 'here' link?

**Comment by dykstranet** [comment]
I'm afraid I have not been able to reproduce this dialogue box.

**Comment by FantasticoFox** [comment]
We could also not reproduce the error. Therefore 'wontfix' for now.
