### ISSUE TITLE
Docker manual start required on Windows (maybe on other platforms too)

### ISSUE THREAD

**Issue by BennSim** [inblockio/micro-PKC#43]
When re starting their machine or rebooting Linux, the user is required to manually start Docker from the Linux command line before running the PKC. Need to automate this step if possible.

**Comment by FantasticoFox** [comment]
We should check if docker is installed and if the server is running. If not and docker IS installed we should start to start the docker-service automatically.

**Comment by FantasticoFox** [comment]
FIXED in https://github.com/inblockio/micro-PKC/commit/fa1c7bdb2be619eb004c9c41cff42b418789544e
