### ISSUE TITLE
[Backup] Database locked after backup

### ISSUE THREAD

**Issue by FantasticoFox** [inblockio/micro-PKC#45]
The wiki becomes unusable after running the backup because the database seems not to be unlocked after the script is run.

![image](https://user-images.githubusercontent.com/45313235/137565380-e1f7a45e-9ef3-4d97-9d03-fa75988323cc.png)

**Comment by FantasticoFox** [comment]
There is also the return to write function which seems not to be triggered. Line 160 and following.

    elif [ $1 == "OFF" ]; then
        # Remove read-only message
        if [ $PRESENT -eq 0 ]; then 
            echo "Returning to write mode"
            sed -i "s/$MSG//ig" "$LOCALSETTINGS"
        else
            echo "Already in write mode"
        fi
    fi

**Comment by FantasticoFox** [comment]
Problem was that the script was executed remotely and the "docker exec -it" was failing the script leading to the unlock-function not being executed correctly.

**Comment by FantasticoFox** [comment]
Fixed in #dc08803b5cbca466578e6586b1c390a7f0c85875

**Comment by FantasticoFox** [comment]
Issue persist after backup on dgov.inblock.io even pulling latest code.
![image](https://user-images.githubusercontent.com/45313235/138192259-f38cd40b-b2f0-4383-90c4-87f23d0c6091.png)

**Comment by FantasticoFox** [comment]
The problem is that NOT the LocalSettings IN the container holds the flag 'Backup in Progress' but the one which is in mountpoint/backup/LocalSettings.php as long as the flag is present there, the DB stays locked.

We should re-evaluate the value and usage of the LocalSettings.php in the backup folder.

**Comment by rht** [comment]
The LocalSettings.php in the container is a symlink to the backup one. The backup one is the real one.

**Comment by FantasticoFox** [comment]
Fixed in refactor and current solution.
