### ISSUE TITLE
When running backup / restore, the system fails on verification, edits, and more... Past cache of instance still present.

### ISSUE THREAD

**Issue by FantasticoFox** [inblockio/micro-PKC#61]
Add pkc stop / pkc start after the restore to clear cache.

Not cleaning the cache of the containers results in caching issues which will break verification and pages.

Adding to the restore script pkc stop, wait until done, pkc start - will resolve the issue.

https://github.com/inblockio/DataAccounting/issues/111

**Comment by 0xc0000007b** [comment]
Will keep my eye out for this. Lowering the priority for now and associating with 1.0 since it's not causing a huge fire.

**Comment by FantasticoFox** [comment]
reviewed by @rht
