### ISSUE TITLE
It's not possible to have more then one backup per day - improve naming convention for backups!

### ISSUE THREAD

**Issue by FantasticoFox** [inblockio/micro-PKC#89]
Current backup convention does not include a naming which allows to have multiple backups per day due to namespace collision ;)

Solution proposal: The naming convention of the backup could look like this:

<domain_id>-<domain_name>-YYYYy-MMm-DDd-HHh-SSs-Protocol-version
e.g. 8cd12df890-localhost-2021y-11m-02d-02h-23s_DAv1.0
e.g. 723a239e9f-pkc.inblock.io-2021y-11m-27d-03h-11s_DAv1.0

This adds collision freedom and human readability and directly indicates if the deployment was private or public. This will help in the restore as we can automatically detect based on the 'localhost / domain_id' if it was a web-public deployment.

**Comment by FantasticoFox** [comment]
Makes https://github.com/inblockio/micro-PKC/issues/42 obsolete.

**Comment by rht** [comment]
Closed via https://github.com/inblockio/micro-PKC/commit/24e8adcb4ae3a3995330477ff35d5fc601e72c16
